# Generated by Django 3.2 on 2023-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_user', models.CharField(max_length=255, verbose_name='当前用户')),
                ('chat_user', models.CharField(max_length=255, verbose_name='当前用户的聊天对象')),
                ('room_name', models.CharField(max_length=255, verbose_name='房间名')),
                ('unread_messages', models.IntegerField(default=0, verbose_name='未读消息数')),
            ],
        ),
    ]
