# Generated by Django 3.2 on 2022-12-11 15:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类目名', max_length=30, verbose_name='类目名')),
                ('code', models.CharField(default='', help_text='唯一类目代码', max_length=30, verbose_name='类目代码')),
                ('desc', models.TextField(default='', help_text='类目描述', verbose_name='类目描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='父类目代码')),
            ],
            options={
                'verbose_name': '物品类目',
                'verbose_name_plural': '物品类目',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('property_type', models.IntegerField(choices=[(0, '需求物品'), (1, '提供物品')], help_text='物品是需求条目还是提供条目(1:需求 2:提供)', verbose_name='物品属性')),
                ('emergency', models.IntegerField(choices=[(1, '啥时候都行'), (2, '最好尽快'), (3, '比较紧急'), (4, '很急'), (5, '十万火急')], default=1, help_text='紧急度(only 需求)', verbose_name='紧急度')),
                ('expected_end_time', models.DateTimeField(default=datetime.datetime.now, help_text='预期结束时间点(only 需求)', verbose_name='结束时间')),
                ('goods_sn', models.AutoField(primary_key=True, serialize=False, verbose_name='物品唯一编号')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('address', models.TextField(max_length=100, verbose_name='地址')),
                ('goods_brief', models.TextField(max_length=100, verbose_name='物品简短描述')),
                ('goods_desc', models.TextField(default='', max_length=500, verbose_name='物品详细描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='物品类目')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
            },
        ),
    ]
