# Generated by Django 3.1.1 on 2022-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_rename_name_needs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
