# Generated by Django 3.2.16 on 2022-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='avatar',
            field=models.ImageField(default='D:\\Documents\\3rd_1st\\Software Engineering\\Ringo\\RingoBackend\\media\\default_avatar.png', upload_to='avatar/%Y/%m/%d'),
        ),
    ]
