# Generated by Django 3.1.1 on 2022-12-04 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tyadmin_api_cli.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='唯一类别代码', max_length=30, verbose_name='类别代码')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.goodscategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '物品类别',
                'verbose_name_plural': '物品类别',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.IntegerField(choices=[(0, '需求物品'), (1, '提供物品')], help_text='物品是需求条目还是提供条目(1:需求 2:提供)', verbose_name='物品属性')),
                ('emergency', models.IntegerField(choices=[(1, '不紧急'), (2, '比较紧急'), (3, '十万火急')], help_text='紧急度(only 需求)', verbose_name='紧急度')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='物品唯一编号')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='物品简短描述')),
                ('goods_desc', tyadmin_api_cli.fields.richTextField(default='', verbose_name='物品详细描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='物品类别')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
            },
        ),
    ]
