# 通用错误码
NO_ERR = 0
MAIL_SEND_SUCCESS = 1

EMPTY_DATA = 102
ERR_INVALID_EMAIL = 101
# 错误码：用户注册
ERR_REG_USERNAME_EXIST = 1001
ERR_REG_EMAIL_EXIST = 1002
ERR_REG_WRONG_VERIFICATION = 1003
ERR_REG_VERIFICATION_REQUEST_TOO_FREQUENT = 1004
# 错误码：用户更改密码
ERR_PWDCHANGE_EMAIL_NOTEXIST = 2001
ERR_PWDCHANGE_VERIFY_FAIL = 2002
ERR_PWDCHANGE_VERIFY_TOO_FREQUENT = 2003
ERR_PWDCHANGE_WRONGPWD = 2004
ERROR_CODE = 'errorCode'