# Generated by Django 3.1.1 on 2022-12-07 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('property_type', models.IntegerField(choices=[(0, '需求物品'), (1, '提供物品')], help_text='物品是需求条目还是提供条目(1:需求 2:提供)', verbose_name='物品属性')),
                ('category', models.IntegerField(choices=[(0, '食品'), (1, '药品'), (2, '生活用品'), (3, '娱乐'), (4, '器械')], help_text='物品种类', verbose_name='种类')),
                ('emergency', models.IntegerField(choices=[(1, '啥时候都行'), (2, '最好尽快'), (3, '比较紧急'), (4, '很急'), (5, '十万火急')], default=1, help_text='紧急度(only 需求)', verbose_name='紧急度')),
                ('expected_end_time', models.DateTimeField(default=datetime.datetime.now, help_text='预期结束时间点(only 需求)', verbose_name='结束时间')),
                ('goods_sn', models.AutoField(primary_key=True, serialize=False, verbose_name='物品唯一编号')),
                ('user', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('address', models.TextField(max_length=100, verbose_name='地址')),
                ('goods_brief', models.TextField(max_length=100, verbose_name='物品简短描述')),
                ('goods_desc', models.TextField(default='', max_length=500, verbose_name='物品详细描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
            },
        ),
    ]
