# Generated by Django 3.1.1 on 2022-12-07 04:58

import datetime
from django.db import migrations, models
import tyadmin_api_cli.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.IntegerField(choices=[(0, '需求物品'), (1, '提供物品')], help_text='物品是需求条目还是提供条目(1:需求 2:提供)', verbose_name='物品属性')),
                ('category', models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6')], help_text='物品种类', verbose_name='种类')),
                ('emergency', models.IntegerField(choices=[(1, '不紧急'), (2, '比较紧急'), (3, '十万火急')], help_text='紧急度(only 需求)', verbose_name='紧急度')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='物品唯一编号')),
                ('user', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='物品简短描述')),
                ('goods_desc', tyadmin_api_cli.fields.richTextField(default='', verbose_name='物品详细描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
            },
        ),
    ]
