# Generated by Django 3.1.1 on 2022-12-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='id',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='物品唯一编号'),
        ),
    ]
