# Generated by Django 3.1.1 on 2022-12-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20221207_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.IntegerField(choices=[(0, '食品'), (1, '药品'), (2, '生活用品'), (3, '娱乐'), (4, '器械')], help_text='物品种类', verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='emergency',
            field=models.IntegerField(choices=[(1, '啥时候都行'), (2, '最好尽快'), (3, '比较紧急'), (4, '很急'), (5, '十万火急')], help_text='紧急度(only 需求)', verbose_name='紧急度'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(max_length=100, verbose_name='物品简短描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=models.TextField(default='', max_length=500, verbose_name='物品详细描述'),
        ),
    ]
