# Generated by Django 3.2 on 2022-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20221226_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default='2022-12-26 16:59:03', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='address',
            field=models.TextField(default='', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='expected_end_time',
            field=models.DateTimeField(default='2022-12-26 16:59:03', help_text='预期结束时间点(only 需求)', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(default='', max_length=100, verbose_name='物品简短描述'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default='2022-12-26 16:59:03', verbose_name='添加时间'),
        ),
    ]
