# Generated by Django 3.2 on 2022-12-26 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20221226_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 9, 1, 16, 119872, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='expected_end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 9, 1, 16, 109875, tzinfo=utc), help_text='预期结束时间点(only 需求)', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 9, 1, 16, 109875, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
