# Generated by Django 3.2 on 2022-12-29 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20221226_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 19, 10, 19, 448624), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='expected_end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 19, 10, 19, 448624), help_text='预期结束时间点(only 需求)', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 19, 10, 19, 448624), verbose_name='添加时间'),
        ),
    ]
